// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using generator_web.Models;

#nullable disable

namespace generator_web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250927234732_ControlAction")]
    partial class ControlAction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("generator_web.Models.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("generator_web.Models.ControlAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("IsExecuted")
                        .HasColumnType("bit");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ControlActions");
                });

            modelBuilder.Entity("generator_web.Models.generator_data", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BataryaVoltaji")
                        .HasColumnType("int");

                    b.Property<string>("CalismaDurumu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenGucFaktoru")
                        .HasColumnType("int");

                    b.Property<int>("GenHz")
                        .HasColumnType("int");

                    b.Property<int>("GenUretilenGuc")
                        .HasColumnType("int");

                    b.Property<int>("GenVoltaj_l1")
                        .HasColumnType("int");

                    b.Property<int>("GenVoltaj_l2")
                        .HasColumnType("int");

                    b.Property<int>("GenVoltaj_l3")
                        .HasColumnType("int");

                    b.Property<int>("MotorRpm")
                        .HasColumnType("int");

                    b.Property<int>("MotorSicaklik")
                        .HasColumnType("int");

                    b.Property<int>("OperationMode")
                        .HasColumnType("int");

                    b.Property<bool>("SebekeDurumu")
                        .HasColumnType("bit");

                    b.Property<int>("SebekeHz")
                        .HasColumnType("int");

                    b.Property<int>("SebekeVoltaj_l1")
                        .HasColumnType("int");

                    b.Property<int>("SebekeVoltaj_l2")
                        .HasColumnType("int");

                    b.Property<int>("SebekeVoltaj_l3")
                        .HasColumnType("int");

                    b.Property<int>("SistemCalismaSuresi")
                        .HasColumnType("int");

                    b.Property<int>("ToplamGuc")
                        .HasColumnType("int");

                    b.Property<int>("YagBasinci")
                        .HasColumnType("int");

                    b.Property<int>("YakitSeviyesi")
                        .HasColumnType("int");

                    b.Property<int>("timestamp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("generator_datas");
                });

            modelBuilder.Entity("generator_web.Models.user_data", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("command")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.ToTable("user_datas");
                });
#pragma warning restore 612, 618
        }
    }
}
