// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using generator_web.Models;

#nullable disable

namespace generator_web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("generator_web.Models.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("generator_web.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("generator_web.Models.generator_data", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BataryaVoltaji")
                        .HasColumnType("int");

                    b.Property<string>("CalismaDurumu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenGucFaktoru")
                        .HasColumnType("int");

                    b.Property<int>("GenHz")
                        .HasColumnType("int");

                    b.Property<int>("GenUretilenGuc")
                        .HasColumnType("int");

                    b.Property<int>("GenVoltaj_l1")
                        .HasColumnType("int");

                    b.Property<int>("GenVoltaj_l2")
                        .HasColumnType("int");

                    b.Property<int>("GenVoltaj_l3")
                        .HasColumnType("int");

                    b.Property<int>("MotorRpm")
                        .HasColumnType("int");

                    b.Property<int>("MotorSicaklik")
                        .HasColumnType("int");

                    b.Property<int>("OperationMode")
                        .HasColumnType("int");

                    b.Property<bool>("SebekeDurumu")
                        .HasColumnType("bit");

                    b.Property<int>("SebekeHz")
                        .HasColumnType("int");

                    b.Property<int>("SebekeVoltaj_l1")
                        .HasColumnType("int");

                    b.Property<int>("SebekeVoltaj_l2")
                        .HasColumnType("int");

                    b.Property<int>("SebekeVoltaj_l3")
                        .HasColumnType("int");

                    b.Property<int>("SistemCalismaSuresi")
                        .HasColumnType("int");

                    b.Property<int>("ToplamGuc")
                        .HasColumnType("int");

                    b.Property<int>("YagBasinci")
                        .HasColumnType("int");

                    b.Property<int>("YakitSeviyesi")
                        .HasColumnType("int");

                    b.Property<int>("timestamp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("generator_datas");
                });
#pragma warning restore 612, 618
        }
    }
}
